# Generated by Django 4.2.7 on 2023-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreightParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('freight', models.FloatField()),
                ('stevedoring_POL', models.FloatField()),
                ('stevedoring_POD', models.FloatField()),
                ('BAF', models.FloatField()),
                ('ISPS', models.FloatField()),
                ('FFPOL', models.FloatField()),
                ('el_connection', models.FloatField()),
                ('ADR', models.FloatField()),
                ('tr_declaration', models.FloatField()),
            ],
        ),
    ]
