# Generated by Django 4.2.7 on 2023-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_freight', '0002_remove_freightparams_ffpol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stevedoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevedoring_1', models.FloatField(default=0)),
                ('stevedoring_2', models.FloatField(default=0)),
                ('stevedoring_3', models.FloatField(default=0)),
                ('stevedoring_nodriver_1', models.FloatField(default=0)),
                ('stevedoring_nodriver_2', models.FloatField(default=0)),
                ('stevedoring_nodriver_3', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='freightparams',
            name='stevedoring_1',
        ),
        migrations.RemoveField(
            model_name='freightparams',
            name='stevedoring_2',
        ),
        migrations.RemoveField(
            model_name='freightparams',
            name='stevedoring_3',
        ),
        migrations.RemoveField(
            model_name='freightparams',
            name='stevedoring_nodriver_1',
        ),
        migrations.RemoveField(
            model_name='freightparams',
            name='stevedoring_nodriver_2',
        ),
        migrations.RemoveField(
            model_name='freightparams',
            name='stevedoring_nodriver_3',
        ),
        migrations.AddField(
            model_name='freightparams',
            name='stevedoring_pod',
            field=models.ManyToManyField(blank=True, related_name='stevpod', to='calculator_freight.stevedoring'),
        ),
        migrations.AddField(
            model_name='freightparams',
            name='stevedoring_pol',
            field=models.ManyToManyField(blank=True, related_name='stevpol', to='calculator_freight.stevedoring'),
        ),
    ]
