# Generated by Django 4.2.7 on 2023-11-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_freight', '0003_stevedoring_remove_freightparams_stevedoring_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stevedoring',
            name='portname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
